version: '2'
services:
  mysql_db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    #volumes:
    #  - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      # https://blog.mosuke.tech/entry/2018/04/21/basic-mysql-on-docker/
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: keystone
      MYSQL_USER: keystone-admin
      MYSQL_PASSWORD: keystone-pw

  keystone:
    depends_on:
      - mysql_db
    build: .
    links:
      - mysql_db
    ports:
      - "35357:35357"
      - "5000:5000"
    restart: always
    environment:
      # https://docs.openstack.org/liberty/ja/install-guide-ubuntu/keystone-openrc.html
      OS_USERNAME: admin
      OS_PASSWORD: ADMIN_PASS
      OS_PROJECT_NAME: admin
      OS_USER_DOMAIN_NAME: Default
      OS_PROJECT_DOMAIN_NAME: Default
      OS_IDENTITY_API_VERSION: 3
      OS_AUTH_URL: "http://localhost:5000/v3"

